# --------------------------------------------------------------------------------
# kustomization.yaml
# The main file that defines a Kustomization. It combines all the manifest files
# and uses a ConfigMapGenerator to create the Nginx configuration.
# --------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
configMapGenerator:
- name: nginx-config
  files:
  - nginx.conf